# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from zapier_actions_python_sdk import ZapierActions

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        zapieractions = ZapierActions(
        
                        access_point_api_key_header = 'YOUR_API_KEY',
        
                        access_point_api_key_query = 'YOUR_API_KEY',
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',,
        
                        session_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(zapieractions)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
