# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from zapier_actions_python_sdk.paths.api_v1_check.get import AuthTestGet
from zapier_actions_python_sdk.apis.tags.check_api_raw import CheckApiRaw


class CheckApi(
    AuthTestGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CheckApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CheckApiRaw(api_client)
