# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import zapier_actions_python_sdk
from zapier_actions_python_sdk.model.error_response import ErrorResponse
from zapier_actions_python_sdk import configuration


class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
