# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from zapier_actions_python_sdk.type.execute_response_additional_results import ExecuteResponseAdditionalResults

class RequiredExecuteResponse(TypedDict):
    # The id of the execution log.
    id: str

    # The name of the action that was executed.
    action_used: str

    # The params we used / will use to execute the action.
    input_params: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    # The URL to run the action or review the AI choices the AI made for input_params given instructions.
    review_url: str

    additional_results: ExecuteResponseAdditionalResults

class OptionalExecuteResponse(TypedDict, total=False):
    # A trimmed down result of the first item of the full results. Ideal for humans and language models!
    result: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    # Human readable labels for some of the keys in the result.
    result_field_labels: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    # The status of the execution.
    status: str

    # The error message if the execution failed.
    error: str

    # A hint for the assistant on what to do next.
    assistant_hint: str

class ExecuteResponse(RequiredExecuteResponse, OptionalExecuteResponse):
    pass
