# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from zapier_actions_python_sdk.type.exposed_action_schema import ExposedActionSchema

class RequiredExposedActionResponseSchema(TypedDict):
    results: typing.List[ExposedActionSchema]

    # URL to configure and expose more actions.
    configuration_link: str

class OptionalExposedActionResponseSchema(TypedDict, total=False):
    pass

class ExposedActionResponseSchema(RequiredExposedActionResponseSchema, OptionalExposedActionResponseSchema):
    pass
