# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExposedActionSchema(TypedDict):
    # Description of the action.
    description: str

    # The unique ID of the exposed action.
    id: str

    # The operation ID of the exposed action.
    operation_id: str

    # Available hint fields for the action.
    params: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class OptionalExposedActionSchema(TypedDict, total=False):
    pass

class ExposedActionSchema(RequiredExposedActionSchema, OptionalExposedActionSchema):
    pass
