# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import zapier_actions_python_sdk
from zapier_actions_python_sdk.paths.api_v1_exposed_exposed_app_action_id_execute import post
from zapier_actions_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV1ExposedExposedAppActionIdExecute(ApiTestMixin, unittest.TestCase):
    """
    ApiV1ExposedExposedAppActionIdExecute unit test stubs
        Execute App Action Endpoint
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
