# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from zapier_actions_python_sdk.pydantic.execute_response_additional_results import ExecuteResponseAdditionalResults

class ExecuteResponse(BaseModel):
    # The id of the execution log.
    id: str = Field(alias='id')

    # The name of the action that was executed.
    action_used: str = Field(alias='action_used')

    # The params we used / will use to execute the action.
    input_params: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(alias='input_params')

    # The URL to run the action or review the AI choices the AI made for input_params given instructions.
    review_url: str = Field(alias='review_url')

    additional_results: ExecuteResponseAdditionalResults = Field(alias='additional_results')

    # A trimmed down result of the first item of the full results. Ideal for humans and language models!
    result: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='result')

    # Human readable labels for some of the keys in the result.
    result_field_labels: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='result_field_labels')

    # The status of the execution.
    status: typing.Optional[Literal["success", "error", "empty", "preview"]] = Field(None, alias='status')

    # The error message if the execution failed.
    error: typing.Optional[str] = Field(None, alias='error')

    # A hint for the assistant on what to do next.
    assistant_hint: typing.Optional[str] = Field(None, alias='assistant_hint')
    class Config:
        arbitrary_types_allowed = True
