# coding: utf-8

"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ExposedActionSchema(BaseModel):
    # Description of the action.
    description: str = Field(alias='description')

    # The unique ID of the exposed action.
    id: str = Field(alias='id')

    # The operation ID of the exposed action.
    operation_id: str = Field(alias='operation_id')

    # Available hint fields for the action.
    params: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(alias='params')
    class Config:
        arbitrary_types_allowed = True
