# coding: utf-8
"""
    Zapier AI Actions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from zapier_actions_python_sdk.client_custom import ClientCustom
from zapier_actions_python_sdk.configuration import Configuration
from zapier_actions_python_sdk.api_client import ApiClient
from zapier_actions_python_sdk.type_util import copy_signature
from zapier_actions_python_sdk.apis.tags.action_api import ActionApi
from zapier_actions_python_sdk.apis.tags.check_api import CheckApi
from zapier_actions_python_sdk.apis.tags.configuration_api import ConfigurationApi
from zapier_actions_python_sdk.apis.tags.log_api import LogApi



class ZapierActions(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.action: ActionApi = ActionApi(api_client)
        self.check: CheckApi = CheckApi(api_client)
        self.configuration: ConfigurationApi = ConfigurationApi(api_client)
        self.log: LogApi = LogApi(api_client)
